### PR TITLE
tickets/PREOPS-3620

### PR DESCRIPTION
**Pull request by MelissaGraham**
Fix DiaObject ra, dec, radecTai descriptions.

### CODE REVIEW

**Comment by gpdf** [comment]
@MelissaGraham Could you rebase this and force-push, please?  We have changed some of the CI workflows and would like to have the new CI picked up before merging this.  Thanks!

**Comment by MelissaGraham** [comment]
Rebased. Merge awaiting confirmation that the new definitions should be adopted. Conversation in comments of PREOPS-3620 ongoing.

**Review by gpdf — COMMENTED** [review]
House style so far has been - and is elsewhere in this file - to begin the `description:` elements with capital letters.

**Comment by MelissaGraham** [comment]
> House style so far has been - and is elsewhere in this file - to begin the `description:` elements with capital letters.

Thank you! Updated to start with a capital letter.

**Review by gpdf — APPROVED** [review]
Looks good now.  Needs one more rebase before merging.

**Pull request merged**
