### PR TITLE
DM-47308: Increment minor version of cdb_lsstcomcam and add electron UCDs

### PR DESCRIPTION
**Pull request by kadrlica**
I've incremented the minor version to 3.5.0 in preparation for the deployment of some new columns and documentation.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
I also have a question about updating the version. This would typically be done along with the addition of the columns. Have the columns you mentioned already been added or is this just planned to occur?

**Comment by kadrlica** [comment]
Right, I think we missed the version updating in the (multiple?) PRs that added columns. [#266](https://github.com/lsst/sdm_schemas/pull/266/files#diff-8abd190cee269f768f06c9ed6059213840779a2e88e4126419fafb15d8d28770) is one example, and there may be others.

**Comment by JeremyMcCormick** [comment]
This should really be two PRs for the version bump and unit/UCDs though I'm not sure how picky I want to be about it. 🙂

**Review by gpdf — APPROVED** [review]
The UCDs and units seem appropriate and reflect an extended conversation.

I note that the version number change being made here should have been part of the PR that added the columns.  We need to improve our procedures to ensure that that's considered in reviews.

I've asked @JeremyMcCormick to add a template checklist for PRs on this repo as a reminder to maintain schema versions appropriately.

**Pull request merged**
