### PR TITLE
DM-44825: Remove datatype overrides on timestamp types and specify precision

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
With the introduction of a precision attribute in Felis, as well as the mapping of timestamp to MySQL `DATETIME`, datatype overrides on timestamp columns should no longer be needed.

[DM-44825]: https://rubinobs.atlassian.net/browse/DM-44825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ktlim — APPROVED** [review]
The CDB changes look good to me.

**Comment by timj** [comment]
For your build problem, it would be useful to adopt the middleware approach to this.

* Add a requirements.txt file with content `lsst-felis @ git+https://github.com/lsst/felis@main`
* Change the build.yaml action to use `pip install -r requirements.txt`
* When you need to build against a ticket branch change the requirements.txt file (the `@main` bit)
* Add the `do_not_merge.yaml` action from daf_butler to prevent you merging with a ticket branch hard coded.

**Comment by JeremyMcCormick** [comment]
> For your build problem, it would be useful to adopt the middleware approach to this.
> 
> * Add a requirements.txt file with content `lsst-felis @ git+https://github.com/lsst/felis@main`
> * Change the build.yaml action to use `pip install -r requirements.txt`
> * When you need to build against a ticket branch change the requirements.txt file (the `@main` bit)
> * Add the `do_not_merge.yaml` action from daf_butler to prevent you merging with a ticket branch hard coded.

Thank you for the suggestion. I'll consider this and make a ticket including this information.

**Review by gpdf — COMMENTED** [review]
Let's proceed with this, it's been pending for a long time, but for the future I'd very much prefer if changes to the data model are not mixed with changes to the software/workflows/etc. *unless the one actually depends on the other*.  It makes rollbacks much messier.

**Comment by gpdf** [comment]
We missed in review that the timestamp changes were applied inconsistently to the 1-year and 10-year DP0.3 schemas.  Fixed up under #240 .

**Pull request merged**
