### PR TITLE
PREOPS-4974: Implement minor corrections to column descriptions in DP0.2 schema

### PR DESCRIPTION
**Pull request by ameisner**
Implements various relatively minor updates to the DP02 schema YAML file. All edits are intended to only affect the "description" field.

### CODE REVIEW

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
These all look like good corrections.

@ameisner Can you rebase all these small commits into a single one?

Here's how you can do this from your ticket branch:

```
git pull origin main
git rebase -i main
```

The last command will give you a list of your commits that looks like:

```
pick e6ff648 Remove UCDs for Visit.expMidpt and Visit.expMidpt in DP0.2 schema
pick 93d0494 GaaP capitalization                                        
pick 6a9508d remove "pseudo-filter"   
...
```

Change `pick` on the first line to `reword.`

Change every other line after the first one so that `pick` is replaced with `f` or `fixup`, which means these commits will be squashed into the first one.

Continue with the rebase (this is `wq` in vim or just close whatever editor you are using).

You will now be able to edit the single commit. Reword the first line to be a summary such as "Implement minor corrections to DP0.2 column descriptions". Include whatever additional text/explanation you want after the body with additional notes on what you have changed. You don't need to list the details of every change that was made.

Exit from editing the first commit and it should rebase.

Now force push your branch:

```
git push -f
```

Before you start, you may want to save your work onto another branch like `git branch -b tickets/PREOPS-4974-backup` or just copy the schema to a local ".bak" file since you are just changing one file.

**Comment by ameisner** [comment]
@JeremyMcCormick -- unless I'm not understanding the GitHub review system sufficiently well, I think your one review comment was to perform the rebase? I did the rebase earlier today with your help, so then I just re-requested your review. Apologies if I'm failing to use GitHub's review functionality optimally here...

**Comment by JeremyMcCormick** [comment]
> @JeremyMcCormick -- unless I'm not understanding the GitHub review system sufficiently well, I think your one review comment was to perform the rebase? I did the rebase earlier today with your help, so then I just re-requested your review. Apologies if I'm failing to use GitHub's review functionality optimally here...

Actually, in the future, you do not need to re-request a review if you resolved the initial request. Instead, the reviewer would just see your updates and approve the PR.

**Review by gpdf — APPROVED** [review]
Looks good to me, but note that there's now the technical debt, as it were, of applying these changes to the corresponding columns in `imsim.yaml` and `hsc.yaml`.

**Review by JeremyMcCormick — APPROVED** [review]

**Pull request merged**
