### PR TITLE
DM-46273: Add Python packaging with ResourcePath support

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
Added Python project packaging with standard `pyproject.toml` file so the project is PIP installable.

Additionally, support is included for accessing the YAML schema files as package resources using a `ResourcePath`, e.g.

```
ResourcePath("resource://lsst.sdm_schemas/schemas/dp02_dc2.yaml")
```

The YAML files were left in place and the top level `yml` directory is symlinked from the Python tree.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
@timj 

Currently the resource paths look like:

```
resource://lsst.sdm_schemas/dp02_dc2.yaml
```

I'm considering if it would be better to have a schemas sub-directory so:

```
resource://lsst.sdm_schemas/schemas/dp02_dc2.yaml
```

It feels a bit redundant in terms of semantics, but it would make the packaging cleaner. (We then wouldn't need an `__init__.py` in the `yml` directory.)

**Comment by JeremyMcCormick** [comment]
> @timj
> 
> Currently the resource paths look like:
> 
> ```
> resource://lsst.sdm_schemas/dp02_dc2.yaml
> ```
> 
> I'm considering if it would be better to have a schemas sub-directory so:
> 
> ```
> resource://lsst.sdm_schemas/schemas/dp02_dc2.yaml
> ```
> 
> It feels a bit redundant in terms of semantics, but it would make the packaging cleaner. (We then wouldn't need an `__init__.py` in the `yml` directory, and `schemas` could be symlinked to the data directory.)

I went ahead and updated this to include the `schemas` directory. This should be more flexible and makes the packaging cleaner. 

I could anticipate we might eventually make available additional resources other than the YAML schema files, so this should make it easier to do this as well.

**Review by timj — APPROVED** [review]
This arrangement works for me.

It would be nice if there was a test for this, even if it wasn't using ResourcePath directly but was using importlib.resources (I can't remember if felis now depends on ResourcePath).

**Comment by JeremyMcCormick** [comment]
@timj 

> It would be nice if there was a test for this

Were you thinking that there should be a test in the sdm_schemas project or felis? (Sounds like maybe you meant felis.)

> (I can't remember if felis now depends on ResourcePath).

Felis will use `ResourcePath` after https://github.com/lsst/felis/pull/90 is merged.

**Comment by timj** [comment]
Re tests: You could use importlib.resources directly as a simple test in sdm_schemas to prove that a yaml file can be found as a package resource.

Re felis, I'm not sure the dependency direction you are thinking because neither depends on the other from what I can tell.

**Comment by JeremyMcCormick** [comment]
> Re tests: You could use importlib.resources directly as a simple test in sdm_schemas to prove that a yaml file can be found as a package resource.
> 
> Re felis, I'm not sure the dependency direction you are thinking because neither depends on the other from what I can tell.

I went ahead and added a test to this PR which checks that a schema resource can be read successfully using `importlib`.

**Pull request merged**
