### PR TITLE
DM-35174-v23: Backport descriptions for DiaObject

### PR DESCRIPTION
**Pull request by yalsayyad**

### CODE REVIEW

**Comment by ctslater** [comment]
I merged the two build fixes from KT on another ticket, so those should rebase away.

**Comment by gpdf** [comment]
What, if anything, still needs to be done with this branch?

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
If this PR is still planned to be merged eventually, please revert the changes to `.github/workflows/build.yaml` and `tap-schema/set_schema_index` so that it represents changes to the YAML schema data only. Modifications to scripts and configuration should be evaluated separately from schema updates.

**Comment by JeremyMcCormick** [comment]
No response from multiple attempts to get an update on the status of this ticket. I am closing it as outdated.

**Pull request closed without merging**
