### PR TITLE
DM-46933: Remove references to STREAK mask

### PR DESCRIPTION
**Pull request by TallJimbo**
See DM-45980 for details.

### CODE REVIEW

**Review by parejkoj — COMMENTED** [review]
Since I wrote this, I think it should have someone else review it (nobody had reviewed it on the original PR).

**Review by leeskelvin — APPROVED** [review]

**Comment by JeremyMcCormick** [comment]
Nitpick: Please author your commit messages to follow DM common standards:

https://github.com/lsst/sdm_schemas/commit/aa84e42f2e98b8f6b9dee56567d98b49a48bd146

e.g. this should be somethinf like "Remove ..."

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
See my comment

**Comment by TallJimbo** [comment]
Commit has been reworded.

**Review by JeremyMcCormick — APPROVED** [review]

**Pull request merged**
