### PR TITLE
Re-enable DP0.2 ForcedSourceOnDiaObject

### PR DESCRIPTION
**Pull request by fritzm**

### CODE REVIEW

**Review by gpdf — APPROVED** [review]
Looks basically OK as is.  See #dm-data-model, however - we should add `principal` and `column_index` metadata to make the table more usable in the Portal.

Do you want me to do this on this branch or come back to it later?

**Comment by fritzm** [comment]
@gpdf please just go ahead and push commits here, thanks!

**Comment by gpdf** [comment]
OK, I'll get to it in about an hour, I think.

**Comment by gpdf** [comment]
@fritzm OK to go.  If you want someone else to have a look, please feel free to assign a further review, but I'm happy.

For @ebellm, @yalsayyad, and @ctslater :

Ordering: 
   diaObjectId#, band#, psfFlux#, psfFluxErr#, psfFlux_flag, psfDiffFlux#, psfDiffFluxErr#, psfDiffFlux_flag, ccdVisitId#, forcedSourceOnDiaObjectId#, 
   coord_ra, coord_dec, parentObjectId, tract, patch, skymap, all pixelFlags* (alphabetized), all local* (alphabetized)
(# = principal)

**Comment by gpdf** [comment]
We'll do a post-deployment review on [DM-35950](https://jira.lsstcorp.org/browse/DM-35950).

**Pull request merged**
